name: "Master Build, Test & Deploy"

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

    - name: Set node version
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
      with:
        node-version: '18.x'

    - name: Install
      run: |
        export DETECT_CHROMEDRIVER_VERSION=true
        npm install
        npm run setheapsize

    - name: Lint
      run: npx grunt lint

    - name: Unit Tests
      run: |
        npm test
        npm run testnodeconsumer

    - name: Production Build
      if: success()
      run: npx grunt prod --msg="Version 10 is here! Read about the new features <a href='https://github.com/gchq/CyberChef/wiki/Character-encoding,-EOL-separators,-and-editor-features'>here</a>"

    - name: Generate sitemap
      run: npx grunt exec:sitemap

    - name: UI Tests
      if: success()
      run: |
        sudo apt-get install xvfb
        xvfb-run --server-args="-screen 0 1200x800x24" npx grunt testui

    - name: Prepare for GitHub Pages
      if: success()
      run: npx grunt copy:ghPages

    - name: Deploy to GitHub Pages
      if: success() && github.ref == 'refs/heads/master'
      uses: crazy-max/ghaction-github-pages@df5cc2bfa78282ded844b354faee141f06b41865
      with:
        target_branch: gh-pages
        build_dir: ./build/prod
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
